instanses:
#        Data in volumes for backup
        volumes:
              # name of volume where data storage
              2kola_db:
                    # folders to backup
                    folders:
                          web:
                              path: /var/www
                              basefileName: "webdata"
                              # Where backup must storage
                              send:
                                  toYandex:
                                      yandex_disk:
                                            account: karachungen
                                  email:
                                      email:
                                            to: "karachungen@gmail.com"
                                            from: "backup@sadsad.com"
                              deleteAfter: true





backup_file_send:
       yandex_disk:
              # name of account
              karachungen:
                    token: 324234324
       email:


