instan—Åes:
#        Data in volumes for backup
        volumes:
              # name of volume where data storage
              2kola_db:
                    # folders to backup
                    folders:
                          mysql:
                              #folder in container for backup
                              path: /var/lib/mysql
                              # temporary docker image name where backup will processing
                              tempImage: "busybox"
                              # where local backup file store
                              destFolder: "/home/karachun/backup"
                              # where backup in temporary image store
                              destName: "mysql"
              # name of volume where data storage
              2kola_web:
                    # folders to backup
                    folders:
                          mysql:
                              #folder in container for backup
                              path: /var/www/html
                              # temporary docker image name where backup will processing
                              tempImage: "busybox"
                              # where local backup file store
                              destFolder: "/home/karachun/backup"
                              # where backup in temporary image store
                              destName: "web"
              # name of volume where data storage
              2kola_web_uploads:
                    # folders to backup
                    folders:
                          mysql:
                              #folder in container for backup
                              path: /var/www/html/wp-content/uploads
                              # temporary docker image name where backup will processing
                              tempImage: "busybox"
                              # where local backup file store
                              destFolder: "/home/karachun/backup"
                              # where backup in temporary image store
                              destName: "web_uploads"
#       Running mysqldump in containers
        mysql:
              2koladb:
                  # where local backup file store
                  destFolder: "/home/karachun/backup"
                  # where backup in temporary image store
                  destName: "2kolamysqldump"
                  container: "2kola_mysql"
                  database: "wordpress"
                  user: "2kola"
                  pass: "2kola"
                  mysqldumpParams:
                          - "--skip-add-drop-table"
                          - "--single-transaction"


backup_file_send:
       yandex_disk:
              # name of account
              karachungen:
                    token: 324234324
       email:


